# Site settings
name: 扒皮大叔的技术博客
email: 776764543@qq.com
author: bapidashu
url: http://www.bapidashu.com
resume_site: https://github.com/bapidashu/bapidashu.github.io
github: https://github.com/bapidashu/bapidashu.github.io
baseurl: ""
description: 与大家分享我的爱好和见解
meta_description: 周广平;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: 未曾青梅，青梅枯萎，芬芳满地;不见竹马，竹马老去，相思万里.从此，我爱上的人都很像你
banner: 那时我们有梦，关于文学，关于爱情，关于穿越世界的旅行。如今我们深夜饮酒，杯子碰到一起，都是梦破碎的声音。----北岛。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: bapidashu
highlighter: Pygments

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

FB:
  comments :
    provider : duoshuo
    duoshuo:
        short_name : luoyan35714
    disqus :
        short_name : freudkang
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light